# Generated by Django 2.2.7 on 2019-11-25 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20191124_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='user_prefers',
            field=models.ManyToManyField(blank=True, related_name='genre_prefers', to=settings.AUTH_USER_MODEL),
        ),
    ]
